/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuizResult = IDL.Record({
  'pittaPercentage' : IDL.Float64,
  'dominantDosha' : IDL.Text,
  'vataPercentage' : IDL.Float64,
  'kaphaPercentage' : IDL.Float64,
});
export const Question = IDL.Record({
  'optionPitta' : IDL.Text,
  'questionText' : IDL.Text,
  'optionKapha' : IDL.Text,
  'optionVata' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'calculatePrakruti' : IDL.Func([IDL.Vec(IDL.Nat)], [QuizResult], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuizResult = IDL.Record({
    'pittaPercentage' : IDL.Float64,
    'dominantDosha' : IDL.Text,
    'vataPercentage' : IDL.Float64,
    'kaphaPercentage' : IDL.Float64,
  });
  const Question = IDL.Record({
    'optionPitta' : IDL.Text,
    'questionText' : IDL.Text,
    'optionKapha' : IDL.Text,
    'optionVata' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'calculatePrakruti' : IDL.Func([IDL.Vec(IDL.Nat)], [QuizResult], ['query']),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };